DROP TABLE IF EXISTS Sensor;
DROP TABLE IF EXISTS Measurement;

CREATE TABLE IF NOT EXISTS Sensor(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(30) CHECK (length(name) >= 3) NOT NULL
);

CREATE TABLE IF NOT EXISTS Measurement(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
	sensor_id int REFERENCES Sensor(id) ON DELETE CASCADE,
	"value" numeric CHECK(value >= 100 AND value <= 100),
	raining boolean
);

ALTER TABLE Measurement ADD COLUMN created_at TIMESTAMP;
ALTER TABLE Sensor ADD UNIQUE (name);