DROP TABLE IF EXISTS Measurement;
DROP TABLE IF EXISTS Sensor;

CREATE TABLE IF NOT EXISTS Sensor(
	name varchar(30) PRIMARY KEY CHECK (length(name) >= 3)
);

CREATE TABLE IF NOT EXISTS Measurement(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
	sensor_name varchar REFERENCES Sensor(name) ON DELETE CASCADE NOT NULL,
	"value" numeric NOT NULL CHECK(value >= -100 AND value <= 100),
	raining boolean NOT NULL,
	created_at DATE
);
